const HEXCELL_WIDTH = 66;
const HEXCELL_HEIGHT = 76;

const VERTICAL_STEP = 57;
const HORIZONTAL_STEP = HEXCELL_WIDTH;
const SEMI_HORIZONTAL_STEP = HORIZONTAL_STEP / 2;

const SPEED_X = 3;
const SPEED_Y = SPEED_X;

export {
   HEXCELL_WIDTH,
   HEXCELL_HEIGHT,
   VERTICAL_STEP,
   HORIZONTAL_STEP,
   SEMI_HORIZONTAL_STEP,
   SPEED_X,
   SPEED_Y,
};
